image: gradle:alpine

stages:
  - test

check:
  stage: test
  needs: []
  script: gradle --build-cache check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    when: always
    paths:
      - build/reports/tests/test/
      - build/reports/checkstyle/
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  allow_failure: false
